name: Demo

on:
  push:
    tags:
      - "*.*.*"

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: "3.7"
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install NetSM
        run: pip install netsm
      - name: Shows the version of the project
        run: netsm version
      - name: Shows information about networks
        run: netsm show --incessant False
